version: "2"
services:
  # claps:
  #   image: golang
  #   volumes:
  #     - .:/go/src/github.com/realitycheck/claps
  #   working_dir: /go/src/github.com/realitycheck/claps
  #   command: go run main.go
  nats.server:
    image: nats
    ports:
      - 4222:4222
      - 8222:8222
  nats.test:
    build:
      context: .
    command: -s nats://nats.server:4222 -c nats -nc 1000 -debug
    links: ["nats.server"]
  cent.server:
    image: centrifugo/centrifugo
    ports:
      - 8000:8000
    command: centrifugo --admin --admin_insecure --client_insecure --api_insecure --debug
  cent.test:
    build:
      context: .
    command: -s ws://cent.server:8000/connection/websocket -c cent -nc 1000 -debug
    links: ["cent.server"]
  ws.server:
    build: 
      context: 
        ./docker/nginx
    volumes: 
      - ./docker/nginx:/data:ro
    ports:
      - 8080:8080
    command: nginx -c /data/nginx.conf -g "daemon off;"
  ws.test:
    build: 
      context: .   
    command: -s ws://ws.server:8080/ws -c ws -nc 1000 -debug
    links: ["ws.server"]